Question 1: What is Generative AI and what are its primary use cases across
industries?

->Generative AI is a type of Artificial Intelligence that can create new content such as text, images, audio, video, or code by learning patterns from data.

Primary Use Cases Across Industries:

Healthcare: medical reports, drug discovery

Finance: fraud detection, financial analysis

Marketing: content creation, ads, product descriptions

Software Development: automatic code generation (e.g., GitHub Copilot)

Media & Entertainment: image, music, and video generation (e.g., DALL·E)

Education: AI tutors, learning materials

Customer Support: chatbots and virtual assistants

Question 2: Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?

->Probabilistic modeling in generative models:
Generative models use probability distributions to learn how data is generated. They model the joint probability
𝑃
(
𝑋
,
𝑌
)
P(X,Y) or the data distribution
𝑃
(
𝑋
)
P(X) and then generate new data samples similar to the training data.

Example:
Models like GAN and Variational Autoencoder learn the probability distribution of the data and generate new images, text, etc.

Difference between Generative and Discriminative models:

Generative Models:
Learn how data is generated and model
𝑃
(
𝑋
,
𝑌
)
P(X,Y).
Can generate new data.

Discriminative Models:
Learn the decision boundary between classes and model
𝑃
(
𝑌
∣
𝑋
)
P(Y∣X).
Used mainly for classification or prediction.

Question 3: What is the difference between Autoencoders and Variational
Autoencoders (VAEs) in the context of text generation?

->Autoencoders:
They learn to compress text into a hidden representation and then reconstruct the same text. They mainly focus on reconstruction, not generating new text.

Variational Autoencoders (VAEs):
They learn a probability distribution of the latent space, so they can generate new text samples, not just reconstruct the input.

Example: Variational Autoencoder

Key Difference:

Autoencoder: reconstructs the same input text.

VAE: learns a distribution and generates new text from it.

Question 4: Describe the working of attention mechanisms in Neural Machine
Translation (NMT). Why are they critical?

->In Neural Machine Translation, the attention mechanism helps the model focus on important words of the input sentence while translating.

How it works:

The encoder processes the input sentence.

During translation, the decoder looks at different parts of the input sentence.

Attention gives higher weight to the most relevant words for generating the next word.

Example: Models like Transformer use attention for translation.

Why it is critical:

Handles long sentences better

Improves translation accuracy

Allows the model to focus on relevant words during translation.

Question 5: What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?

->thical considerations in Generative AI for creative content:

Copyright issues: AI may generate content similar to existing works.

Plagiarism: Risk of copying original authors’ style or text.

Bias: AI can produce biased or unfair content if training data is biased.

Misinformation: AI-generated stories or text may spread false information.

Authorship: It can be unclear whether the human or AI should get credit.


In [1]:
'''Question 6: Use the following small text dataset to train a simple Variational
Autoencoder (VAE) for text reconstruction:
["The sky is blue", "The sun is bright", "The grass is green",
"The night is dark", "The stars are shining"]
1. Preprocess the data (tokenize and pad the sequences).
2. Build a basic VAE model for text reconstruction.
3. Train the model and show how it reconstructs or generates similar sentences.
Include your code, explanation, and sample outputs'''

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = [
"The sky is blue",
"The sun is bright",
"The grass is green",
"The night is dark",
"The stars are shining"
]


tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)


max_len = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_len, padding='post')

vocab_size = len(tokenizer.word_index) + 1

print(padded_sequences)

[[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]


In [ ]:
'''Question 7: Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short
English paragraph into French and German. Provide the original and translated text'''

from openai import OpenAI

# Initialize client with API key
client = OpenAI(api_key="api key")

text = "Artificial intelligence is transforming the world. It helps people solve complex problems, improve healthcare, and create new technologies for the future."

prompt = f"""
Translate the following English paragraph into French and German.

English:
{text}

Give the translations clearly.
"""

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": prompt}
    ]
)

print(response.choices[0].message.content)

In [2]:
'''Question 8: Implement a simple attention-based encoder-decoder model for
English-to-Spanish translation using Tensorflow or PyTorch.'''

import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Attention
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

eng = ["hello", "how are you", "good morning", "thank you"]
spa = ["hola", "como estas", "buenos dias", "gracias"]

tok_eng = Tokenizer()
tok_spa = Tokenizer()

tok_eng.fit_on_texts(eng)
tok_spa.fit_on_texts(spa)

eng_seq = tok_eng.texts_to_sequences(eng)
spa_seq = tok_spa.texts_to_sequences(spa)

max_len = max(max(len(i) for i in eng_seq), max(len(i) for i in spa_seq))

eng_seq = pad_sequences(eng_seq, maxlen=max_len, padding="post")
spa_seq = pad_sequences(spa_seq, maxlen=max_len, padding="post")

vocab_eng = len(tok_eng.word_index) + 1
vocab_spa = len(tok_spa.word_index) + 1

encoder_inputs = Input(shape=(max_len,))
enc_emb = Embedding(vocab_eng, 64)(encoder_inputs)
encoder_lstm = LSTM(64, return_sequences=True)
encoder_outputs = encoder_lstm(enc_emb)

attention = Attention()
attention_output = attention([encoder_outputs, encoder_outputs])

decoder_lstm = LSTM(64, return_sequences=True)
decoder_outputs = decoder_lstm(attention_output)

outputs = Dense(vocab_spa, activation="softmax")(decoder_outputs)

model = tf.keras.Model(encoder_inputs, outputs)

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

model.fit(eng_seq, np.expand_dims(spa_seq, -1), epochs=200)

test = tok_eng.texts_to_sequences(["hello"])
test = pad_sequences(test, maxlen=max_len, padding="post")

pred = model.predict(test)

pred_ids = np.argmax(pred[0], axis=1)

reverse_spa = {v:k for k,v in tok_spa.word_index.items()}

translated = " ".join([reverse_spa.get(i,"") for i in pred_ids if i!=0])

print("Input:", "hello")
print("Predicted Spanish:", translated)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.0833 - loss: 1.9458
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 1.9415
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 1.9371
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 1.9324
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 1.9275
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 1.9222
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 1.9164
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 1.9100
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 1.9030
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 1.8951
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 1.8862
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss

In [3]:
'''Question 9: Use the following short poetry dataset to simulate poem generation with a
pre-trained GPT model:
["Roses are red, violets are blue,",
"Sugar is sweet, and so are you.",
"The moon glows bright in silent skies,",
"A bird sings where the soft wind sighs."]
Using this dataset as a reference for poetic structure and language, generate a new 2-4
line poem using a pre-trained GPT model (such as GPT-2). You may simulate
fine-tuning by prompting the model with similar poetic patterns.
Include your code, the prompt used, and the generated poem in your answer.
'''

from transformers import pipeline

poetry_dataset = [
"Roses are red, violets are blue,",
"Sugar is sweet, and so are you.",
"The moon glows bright in silent skies,",
"A bird sings where the soft wind sighs."
]

prompt = """
Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Write a new short poem in the same style:
"""

generator = pipeline("text-generation", model="gpt2")

result = generator(prompt, max_length=60, num_return_sequences=1)

print("Prompt:")
print(prompt)

print("\nGenerated Poem:")
print(result[0]["generated_text"])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Passing `generation_config` together with generation-related arguments=({'num_return_sequences', 'max_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=60) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Prompt:

Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Write a new short poem in the same style:


Generated Poem:

Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

Write a new short poem in the same style:

I am the most beautiful woman

Who doesn't dream of being a woman.

But it's not like you,

My beautiful face.

Write a new short poem in the same style: I'm a woman who's had to struggle with her power.

Read this poem.

I am the most beautiful woman who's had to struggle with her power.

And at this moment it's the most beautiful woman who'll be in my heart.

I am the most beautiful woman who's had to struggle with her power.

I am the most beautiful woman who's had to struggle with her power.

I'm the most beautiful woman who's had to struggle with her power.

I am the most beautiful wom

In [4]:
'''Question 10: Imagine you are building a creative writing assistant for a publishing
company. The assistant should generate story plots and character descriptions using
Generative AI. Describe how you would design the system, including model selection,
training data, bias mitigation, and evaluation methods. Explain the real-world challenges
you might face.'''

'''1. Model Selection
Use a large language model such as GPT-3 or GPT-2 because they are good at generating natural language, story plots, and character descriptions.

2. Training Data
The model would be trained or fine-tuned on:

Books and novels

Short stories and scripts

Character descriptions and plot summaries
This helps the model learn narrative structure, storytelling style, and character development.

3. Bias Mitigation
To reduce bias:

Use diverse datasets from different cultures and authors

Remove harmful or biased text from training data

Apply moderation filters to generated content.

4. Evaluation Methods
The system can be evaluated by:

Human evaluation (editors reviewing story quality)

Coherence and creativity checks

Relevance to the prompt

User feedback from writers and editors.

5. Real-World Challenges

Copyright issues if generated text resembles existing books

Bias in generated stories

Maintaining creativity without repeating patterns

Large computational cost for training and inference

Ensuring ethical and responsible content generation.'''


from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = """
Create a story plot and main character description.

Story Genre: Fantasy

Character:
Name:
Background:
Personality:

Story Plot:
"""

result = generator(prompt, max_length=150, num_return_sequences=1)

print(result[0]["generated_text"])

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=256) and `max_length`(=150) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)



Create a story plot and main character description.

Story Genre: Fantasy

Character:
Name:
Background:
Personality:

Story Plot:

Character:

Name:

Background:

Personality:

Character:

Name:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:

Name:

Background:

Personality:

Character:


